### ISSUE TITLE
arbc-truffle-compile sometimes fails to recognize EVM file suffix

### ISSUE THREAD

**Issue by ewfelten** [OffchainLabs/arbitrum#10]
EVM code files have a suffix at the end that contains metadata that will usually not be valid code. arbc-truffle-compile detects this (because it starts with 0xa165 or 0xa265, depending on solc version) and removes it before trying to translate an EVM code file.

This detection sometimes fails, leading to arbc-truffle-compile reporting invalid instructions at the end of the EVM code.

This seems to be happening because the 0xa165 or 0xa265 sentinel value is inside the immediate argument of an instructions, while arbc-truffle-compile only looks at the opcodes when scanning for the sentinel.

This is weird because in a valid EVM file the sentinel shouldn't be inside an immediate argument--that would make the EVM file, minus metadata, invalid as EVM code., which shouldn't happen.

**Comment by hkalodner** [comment]
This is now resolved. First we corrected our handling of contract metadata. After that we switched over to ignoring code after the first invalid opcode since the compiler inserts raw data into the contract code in order to implement cheap static values.
