### ISSUE TITLE
EthBridge disputable and unanimous tokenNums differs

### ISSUE THREAD

**Issue by ughe** [OffchainLabs/arbitrum#11]
Why is `tokenNums` created using `balance.TokenIndex` for unanimous assertions and `precondition.BeforeBalance.TokenIndex` for disputable assertions?
### balance.TokenIndex

https://github.com/OffchainLabs/arb-validator/blob/f7ca75895afc0095ba006f3c0846ec95916c58ea/ethbridge/ethbridge.go#L568

https://github.com/OffchainLabs/arb-validator/blob/f7ca75895afc0095ba006f3c0846ec95916c58ea/ethbridge/ethbridge.go#L608

https://github.com/OffchainLabs/arb-validator/blob/f7ca75895afc0095ba006f3c0846ec95916c58ea/ethbridge/ethbridge.go#L650

### precondition.BeforeBalance.TokenIndex

https://github.com/OffchainLabs/arb-validator/blob/f7ca75895afc0095ba006f3c0846ec95916c58ea/ethbridge/ethbridge.go#L723

https://github.com/OffchainLabs/arb-validator/blob/f7ca75895afc0095ba006f3c0846ec95916c58ea/ethbridge/ethbridge.go#L689

**Comment by ewfelten** [comment]
@hkalodner, please review this.  I suspect it is now moot and therefore should be closed.

**Comment by hkalodner** [comment]
This is definitely moot with the removal of before balance from the precondition
