### ISSUE TITLE
Specification of addmod instruction is ambiguous

### ISSUE THREAD

**Issue by ewfelten** [OffchainLabs/arbitrum#113]
The specification of addmod, as described in the AVM Spec document, is ambiguous. It doesn't say whether the arguments A, B, and C are treated as signed or unsigned. 

We should clarify the spec (probably by saying all three are treated as unsigned), and add tests to verify that the behavior is consistent with the updated spec.

**Comment by tpobryan** [comment]
We do already have a test ((-1)+1)%7=2 to test that internal addition does not 256-bit truncate. This also shows that the numbers are treated as unsigned. Do we need more tests and if so any suggestions for what to test?

**Comment by ewfelten** [comment]
We might also test something like (3+3)%(-4) = 6, to ensure that the negative-exponent case is handled correctly.

**Comment by ewfelten** [comment]
Fixed by pull request #114.
