### ISSUE TITLE
Assertion should reverse order of imported messages

### ISSUE THREAD

**Issue by edfelten** [OffchainLabs/arbitrum#121]
Every assertion imports a (possibly empty) sequence of messages from the pending inbox into the VM. The pending inbox stores these in a linked list, with newest messages at the head of the list, because that makes it easy for the EthBridge to update a hash accumulator when a new message comes in to the pending inbox. But the VM wants to receive the messages in a linked list with oldest first, i.e. in reverse order from how they're kept by the pending inbox.

It would be nice if a validator, in building an assertion, reversed the order of the linked list of messages. That would reduce work for the VM.

The tricky part is that the assertion includes a sub-assertion about the hash of the transferred segment of messages. We would need to tweak how this sub-assertion is made and bisected, to be consistent with the order-reversal. That's easy in principle but beware off-by-one errors,

**Comment by hkalodner** [comment]
@edfelten I propose we close this assertion on the grounds that we'd prefer to keep the ethbridge code as simple as possible and favor doing this in ArbOS instead

**Comment by edfelten** [comment]
Agree.
