### ISSUE TITLE
arb-ts: 'dotenv' / 'dot-env' module mismatch

### ISSUE THREAD

**Issue by williamsonmatt** [OffchainLabs/arbitrum#1386]
Hi! After adding arb-ts to our project, I'm getting the following error:

ERROR in ./node_modules/arb-ts/dist/lib/networks.js
Module not found: Error: Can't resolve 'dotenv' in '[...]/arb-ts/dist/lib'
 @ ./node_modules/arb-ts/dist/lib/networks.js 7:33-50
 @ ./node_modules/arb-ts/dist/index.js
 @ [...]

It looks like this is because of a mismatch between dependencies and what's actually imported:

'dotenv' is required here: https://github.com/OffchainLabs/arbitrum/blob/master/packages/arb-ts/src/lib/networks.ts#L1

But 'dot-env' is imported here: https://github.com/OffchainLabs/arbitrum/blob/master/packages/arb-ts/package.json

**Comment by DZGoldman** [comment]
thank @williamsonmatt , i went ahead and published the fix in arb-ts version 0.0.27
