### ISSUE TITLE
Shouldn't accept assertions with deadlines far in the future

### ISSUE THREAD

**Issue by edfelten** [OffchainLabs/arbitrum#140]
The EthBridge should reject assertions if their challenge deadline would be too far in the future. This will prevent assertions from running too far ahead of confirmations, thereby keeping the node-tree from getting too large.

**Comment by ewfelten** [comment]
Suggest prohibiting assertions whose deadlines would be more than 2x the grace period in the future.  This would allow asserters to get one grace period ahead of the present (because the deadline is roughly grace period + workahead amount).

**Comment by hkalodner** [comment]
This isn't necessary in the current scheme
