### ISSUE TITLE
Defend against slow-walking attacks

### ISSUE THREAD

**Issue by edfelten** [OffchainLabs/arbitrum#144]
Currently a malicious validator can slow down progress of a chain by submitting small assertions. We want to require validators to submit "as large as reasonably possible" assertions instead.  

We would require validators to import into the pending inbox all messages older than the assertion's lower time bound, and then to have every assertion either (a) end with the VM in a blocked state, or (b) execute some minimum number of steps (relative to the chain's maxSteps limit).

**Comment by edfelten** [comment]
Arguably, this is really only important if a backlog in processing incoming calls starts to accumulate. If that's the concern, we could require every Tx to either (a) take some minimum number of steps (say, half of maxSteps), or (b) supply to the VM all of the on-chain inbox messages up to some recent block number, and if there are any such messages, actually read those into the inbox.  

The advantage of this is that it is reasonably enforceable without changing our current data structures very much.

**Comment by edfelten** [comment]
After some discussion, it seems like the best solution is to require that every assertion satisfy at least one of these two conditions:
(1) the number of instructions executed is at least min(30 seconds of ArbGas, half of maxSteps), or
(2) it executes the inbox instruction and leaves no messages older than 3 blocks in the on-chain inbox.

**Comment by edfelten** [comment]
An alternative rule, which is easier to check given our current data structures, says every assertion must satisfy at least one of three conditions:
(1) number of steps is at least min(30 seconds of ArbGas, half of maxSteps), or
(2) it executes the inbox instruction and moves at least half of the as-yet-unmoved messages in the on-chain inbox into the pending inbox, or
(3) the on-chain inbox has no as-yet-unmoved messages.

**Comment by hkalodner** [comment]
The protocol now has a minimum assertion length based on a number of factors which accomplishes the goals here
