### ISSUE TITLE
Parallelize docker compose

### ISSUE THREAD

**Issue by ughe** [OffchainLabs/arbitrum#15]
Currently `docker-compose build --parallel` does not work because there is a build time dependency of arb-validator on arb-ethbridge. This dependency is because of information needed only at runtime. The files include:

```
ethbridge_addresses.json
validator_private_keys.txt
validator_addresses.txt
```

The build time dependency should be broken to allow parallel builds. The validators need `ethbridge_addresses.json` for the EthBridge contract addresses running on Ganache. This could be resolved at runtime by either:

- Mounting a volume with the addresses
- Or arb-ethbridge serving `ethbridge_addresses.json` to the validators at runtime

Currently validators also receive the list of private keys and public keys during the build phase. By passing the development mnemonic directly to validators, they can generate just their own private key and address.

**Comment by hkalodner** [comment]
Docker compose now only builds a single image so this is no longer relevant
