### ISSUE TITLE
Validators slow and inconsistent in pruning dead nodes

### ISSUE THREAD

**Issue by ewfelten** [OffchainLabs/arbitrum#155]
Validators include a background thread that identifies prunable rollup nodes. This thread needs to be more aggressive (pruning faster) and more consistent (so a particular prunable node doesn't sit unpruned for a long time).

**Comment by ewfelten** [comment]
This seems to have gotten better due to various bug fixes and improvements over time. 

I'm removing the "bug" label because it's now just an issue to monitor and optimize over time.

**Comment by hkalodner** [comment]
This should be improved by #169 which will allow a single transaction to prune multiple nodes

**Comment by ewfelten** [comment]
It looks like #169 has fixed this.  Closing.
