### ISSUE TITLE
Add renBTC to the bridge token list

### ISSUE THREAD

**Issue by lookfirst** [OffchainLabs/arbitrum#1659]
Was trying to figure out all the mechanics for this so I could submit a PR, but alas, I am stumped without some documentation.

I think I saw something in the arb-ts package?

**Comment by DZGoldman** [comment]
yo - trustless bridging will be live in a few weeks; before then you can reach out to us (form in here) https://offchain.medium.com/continued-path-to-decentralization-bridging-tokens-into-arbitrum-42a94b054560
