### ISSUE TITLE
npmjs published libraries

### ISSUE THREAD

**Issue by kr1p70n1c** [OffchainLabs/arbitrum#1750]
Is it possible that all the published `npmjs` libraries can be published under an organisation perhaps, or just with an umbrella name eg:
```
@offchainlabs/*
```
or
```
@arbitrum/*
```

At the moment it is not intuitive or easy to find published `Arbitrum` libraries.  It is very easy to find other projects' libraries with search strings like:
```
@openzeppelin/
```
or
```
@maticnetwork/
```

Is it possible to implement such a `npmjs` deployment strategy like this as well over here @ `Arbitrum`.

kr1p70n1c

**Comment by fionnachan** [comment]
we have packages under both now
see https://www.npmjs.com/search?q=%40offchainlabs
and https://www.npmjs.com/search?q=%40arbitrum
