### ISSUE TITLE
Unify latestConfirmed path proofs in pruneLeaves

### ISSUE THREAD

**Issue by edfelten** [OffchainLabs/arbitrum#176]
The pruneLeaves call to the EthBridge prunes multiple mooted leaves in a single call. For each leaf it wants to prune, it identifies a common ancestor node between that leaf and latestConfirmed, and passes in disjoint path proofs to the leaf and to latestConfirmed.

It would be more efficient to identify a single ancestor node, have a single path proof from that ancestor to latestConfirmed, and then have separate path proofs from the ancestor to each leaf-to-prune (checking that those are disjoint from the latestConfirmed path proof).

**Comment by hkalodner** [comment]
This issue was related to the old rollup protocol which has been superseded by the current version
