### ISSUE TITLE
cant find any description about these two modes: AnyTrust Channels, AnyTrust Sidechains

### ISSUE THREAD

**Issue by predrag-markovic** [OffchainLabs/arbitrum#1781]
I was unable to find any documentation here: https://developer.offchainlabs.com/docs about AnyTrust Channels, AnyTrust Sidechains. (also googled it, but no details)

**Comment by DZGoldman** [comment]
Hey @predrag-markovic - on our roadmap, but neither is currently live yet — brief description of each in the glossary here https://developer.offchainlabs.com/docs/glossary

**Comment by predrag-markovic** [comment]
Got it, thank you for  your info!
