### ISSUE TITLE
[Question] Do I need a token bridge smart contract when I deploy same smart contract on both Ethereum and Arbitrum?

### ISSUE THREAD

**Issue by predrag-markovic** [OffchainLabs/arbitrum#1784]
I have deployed a smart contract AAA that contains token staking, rewards, and fee management.
It works and is deployed on Ethereum Layer 1.
I want to keep this smart contract as it is on Etheruem Layer 1 but also want to deploy it on Arbitrum which does exactly the same function on the Ethereum network.
Do I still need to modify the contract? Do I need to replace all transaction functions with Arbitrum's transaction-related methods? (withdrawEth, etc). I have checked OffChainLabs documentation already but regarding this, I don't have a clear idea.
I want to take Layer1 users to Arbitrum as well.
Do I just need to deploy the same smart contract on Arbitrum but develop a bridge that communities between Ethereum AAA and Arbitrum AAA?
If I deploy AAA contract on Ethereum and Arbitrum both,
then all L2 transaction of AAA on Arbitrum is just the same as L1 transactions of AAA on the Ethereum network?
Do we need just a Bridge contract created for L2 to L1 or L1 to L2 transaction and we deploy exactly the same contract as Ethereum on Arbitrum network?
I have no idea, if someone can help me with it, I would appreciate it.
Thanks

**Comment by fredlacs** [comment]
Hey, these two links in the docs should help you get a clearer idea.

https://developer.offchainlabs.com/docs/l1_l2_messages

https://developer.offchainlabs.com/docs/bridging_assets

The discord server is a more appropriate place for these questions than GitHub issues which we use to track bugs/reports/feature requests
