### ISSUE TITLE
Unable to join discord

### ISSUE THREAD

**Issue by flashdebugger** [OffchainLabs/arbitrum#1839]
### Known Issues

I wanted to join the discord channel using this invite [link](https://discord.com/invite/ZpZuw7p), but it showed an `Unable to accept invite` message.

![image](https://user-images.githubusercontent.com/55588335/142617336-a826ab7e-a48f-4d7d-b9e8-533caf96b8a7.png)

**Comment by fredlacs** [comment]
Seems like that is an old link to join the server. You can join using [this](https://www.discord.gg/5KE54JwyTs) link.

Will update the link on the offchainlabs website.
Feel free to re-open the issue if it doesn't work or you spot the old link somewhere else!

**Comment by flashdebugger** [comment]
@fredlacs thank you. The new link works like a charm.

But all the links on your website didn't work out.
