### ISSUE TITLE
EVM Tracing

### ISSUE THREAD

**Issue by artjoma** [OffchainLabs/arbitrum#1860]
Is it possible add support for SELFDESTRUCT opcode?

https://github.com/OffchainLabs/arbitrum/blob/8e48957257ce42ec9f97ee4da9598fb1d3ec8286/packages/arb-evm/evm/tracing.go#L193

**Comment by joshuacolvin0** [comment]
Please keep all questions to https://discord.gg/arbitrum
Thanks!
