### ISSUE TITLE
Block tracing example

### ISSUE THREAD

**Issue by artjoma** [OffchainLabs/arbitrum#1868]
What is the proper way of block(mainnet or testnet) tracing:

``` mach, err := cmachine.New(*arbosfile) ```
	or 
``` mach, err := server.srv.GetLookup().GetMachineAtBlock(blockNumber, true)  // always return empty array of debug messages ```

```
	// init machine message
	_, _, _, err = mach.ExecuteAssertion(10000000000, false, []inbox.InboxMessage{inboxMessages[0]})
	if err != nil {
		panic(err)
	}

	for i, msg := range inboxMessages[1:] {
	        _, dPrints, _, err := mach.ExecuteAssertion(pTx.Tx.Gas(), false, []inbox.InboxMessage{msg})
		if dPrints != nil {
			ExtractDebugTrace(dPrints, txInfo)
		}

```

Folks, could you please advice or attach some code example.

**Comment by joshuacolvin0** [comment]
Please keep all questions to https://discord.gg/arbitrum
Thanks!
