### ISSUE TITLE
ETH-BRIDGE: Challenger

### ISSUE THREAD

**Issue by r1cs** [OffchainLabs/arbitrum#1896]
Lately I attempt to startChallenge in ethereum main net.But I can only find challengerFactory.I'm concerned that it seems like that your guys haven't achieve the proof?

**Comment by fredlacs** [comment]
Hey, you may find the relevant addresses over in the docs https://developer.offchainlabs.com/docs/useful_addresses#protocol-l1

To start a challenge you need to interact with the rollup contract by calling [this](https://github.com/OffchainLabs/arbitrum/blob/be98be2484f9390ecc2bc01c10ba173a904ecc69/packages/arb-bridge-eth/contracts/rollup/facets/RollupUser.sol#L274) function.
As mentioned in [here](https://developer.offchainlabs.com/docs/mainnet#some-words-of-caution) the validator functions, ie starting a challenge, are currently whitelisted while we're in beta.

Closing this issue, but glad to carry on the conversation in our [discord](https://discord.gg/arbitrum) 👀
