### ISSUE TITLE
Support versioning of ethbridge/protocol

### ISSUE THREAD

**Issue by edfelten** [OffchainLabs/arbitrum#192]
Chain factories and chains should be tagged with a version ID string.  Whenever we make a breaking change to the EthBridge protocol, we should change this.  

When a client connects to a chain, it should get the chain's version number and check it against the expected version.  If this check fails, an error message should direct the user to a documentation page giving advice about how to get compatible software.

**Comment by hkalodner** [comment]
This was added a while ago
