### ISSUE TITLE
Checkpoint inbox more efficiently

### ISSUE THREAD

**Issue by edfelten** [OffchainLabs/arbitrum#193]
The checkpointer could be much more efficient in checkpointing the pending inbox. At the moment it saves a copy of every message every time it checkpoints a chain. 

This means the same message will get saves multiple times.  This isn't as inefficient as one might think, because the low-level checkpointer de-dupes stores Values (and messages are Values).  But it still touches the database once per message, in order to increment the refcount on an already-stored message.

We can eliminate this by building a bespoke checkpointer for the pending inbox.

This isn't a super-high priority at the moment, because checkpointing seems to be efficient enough.  It might matter more for a dapp that receives lots and lots of small messages., and has frequent assertions.

**Comment by hkalodner** [comment]
The new ArbCore stores a single copy of the inbox making it much more efficient than the old system
