### ISSUE TITLE
Bridge on my localhost

### ISSUE THREAD

**Issue by przeor** [OffchainLabs/arbitrum#1955]
Hello,

Since Badger DAO hack, I am very serious on trying avoid centralized hosted front-end for Web3.

I have already installed Uniswap and MakerDAO on my localhost and it works fine. I can't find instruction / repo for doing the same for https://bridge.arbitrum.io/

Any directions how to setup Arbitrum Bridge on my localhost?

Thanks in advance

Regards,
Kamil

**Comment by fredlacs** [comment]
Hey, the repo you're looking for is over at https://github.com/offchainlabs/arb-token-bridge/

**Comment by przeor** [comment]
OK - I see this path https://github.com/OffchainLabs/arb-token-bridge/tree/master/packages/arb-token-bridge-ui

**Comment by przeor** [comment]
> Hey, the repo you're looking for is over at https://github.com/offchainlabs/arb-token-bridge/

Hello @fredlacs , I got an issue:

I did yarn install (success) and yarn start give gives me this error:
```Failed to compile.

./src/tokenLists.tsx
Module not found: Can't resolve 'token-bridge-sdk' in '/Users/market/Desktop/arb-token-bridge/packages/arb-token-bridge-ui/src'```

I am on macos 11.1

Any idea how to install it properly since there is no README.md?

Regards

**Comment by fredlacs** [comment]
You want to `yarn install` at the root of the project.

Please keep questions to https://discord.gg/arbitrum
