### ISSUE TITLE
Contract deployment: "execution ran out of gas" if not setting an explicit gas limit

### ISSUE THREAD

**Issue by d10r** [OffchainLabs/arbitrum#1966]
I'm getting _execution ran out of gas_ for a contract deployment transaction which succeeds if setting an explicit gas limit.  
Looks like gas estimation is failing.  
This happens when deploying the Superfluid protocol via deploy script, see https://github.com/superfluid-finance/protocol-monorepo/issues/564.  
The problem is specific to Arbitrum, wasn't observed on any other EVM chain so far.
If more info is needed, let me know.

**Comment by ki37ki** [comment]
Nice work 👍
