### ISSUE TITLE
Add better windows support

### ISSUE THREAD

**Issue by zbcoding** [OffchainLabs/arbitrum#1975]
or at least add a note to the readme to save dev time.

For instance,
variables in code like $npm_execpath [are not compatible with Windows](https://stackoverflow.com/questions/53883405/npm-execpath-isnt-recognized-as-an-internal-or-external-command-program-or) (which uses %npm_execpath%

**Comment by fredlacs** [comment]
Fixed in https://github.com/OffchainLabs/arbitrum/pull/2101 
should be merged into master soon.
thanks for the report, let us know if you run into any other issues
