### ISSUE TITLE
Bridge Arbitrum ERC20 issue debug question

### ISSUE THREAD

**Issue by przeor** [OffchainLabs/arbitrum#2043]
Hello,

I am bridging ERC20 WIS token (0xDecade1c6Bf2cD9fb89aFad73e4a519C867adcF5) token from L1 to L2 Arbitrum ( https://arbiscan.io/token/0xa0459edcad5aac14dc32775d22ff7bd33027cac7 ).

I was able to bridge successfully less than 1000 WIS tokens, but when I try to bridge more than 1000 WIS I am receiving this error in console log which stops Metamask from opening correctly:

<img width="1253" alt="Screenshot 2022-02-09 at 14 12 54" src="https://user-images.githubusercontent.com/5995/153208243-2a4f1d0d-3e4c-47aa-9148-ddacaf8f0c67.png">

Anyone has ideas, why bridging more than 1000 WIS creates this error in console log ? How I can workaround this issue?

P.S. Error -32000 execution reverted on metamask details:
<img width="317" alt="Screenshot 2022-02-09 at 14 14 09" src="https://user-images.githubusercontent.com/5995/153208450-99756643-450c-4e71-a9bb-1c48cfd51c95.png">

**Comment by fredlacs** [comment]
Please keep questions to https://discord.gg/arbitrum

https://github.com/OffchainLabs/arbitrum/issues/1955#issuecomment-1016336483
