### ISSUE TITLE
Upgrade openzeppelin contracts version

### ISSUE THREAD

**Issue by rahul-kothari** [OffchainLabs/arbitrum#2067]
https://github.com/OffchainLabs/arbitrum/blob/master/packages/arb-bridge-peripherals/package.json#L28

Openzeppelin's current version is 4.5. And it uses solidity v0.8 whereas this package uses openzeppelin v3.4 which uses solidity >=0.6 <0.8

It prevents people from using the bridge contracts with solidity v0.8

**Comment by fredlacs** [comment]
The code here is pinned to use solc 0.6.11.
You may use the necessary interfaces yourself to interact from v0.8 instead of the whole code.
