### ISSUE TITLE
[Transactions] Invalid Transaction Nonce Every Now and Then ⚡ 

### ISSUE THREAD

**Issue by BMItr** [OffchainLabs/arbitrum#2127]
Greetings 🖖 

in the last days I made much testing on Arbitrum and fired several transactions!
Its blazing fast and the transaction costs are very fair. Appreciation for that achievement! 🥇 🚀 

- **Actual Behaviour / Overview:**

Unfortunally every 3th or 4th transaction failes with the message: '_invalid transaction nonce_'  (code -32000) 

- **Expected Behaviour**

Every transaction submitted to Arbitrum will burn a nonce...
see official [Arbitrum-Link](https://developer.offchainlabs.com/docs/differences_overview#:~:text=Nonces,not%20have%20the%20expected%20nonce.) 

- **Info1:**

I tested several public Arbitrum RPCs (Nodes) and it happens on all RPCs like _Harmony, Alchemy, Infura_ etc. and also on the offical _https://arb1.arbitrum.io/rpc_ and also on local test-setups.

- **Info2:**

Its is not related to insufficent gas or wrong settings.
I personally use Web3 (python/JS) to fire my transactions, but people are seeing it also on Browser/Metamask/other UIs...

- **Example:**

If you fire a transaction you usually get the matching transaction nonce e.g. '2', '3', '4' etc. (like a counter)
But sometimes the RPCs are expecting very strange nonce values leading to errors, like:
![image](https://user-images.githubusercontent.com/46747780/159494291-4037d782-193f-433b-a6ad-18c837db6f48.png)

**If you already know this little annonying issue please simply forget this ticket..
But as developers cannot have their eyes & ears everywhere, feel invited to make arbitrum a little bit better as it already is** :octocat: 

---------------------------------------------------------------------------------------

_Other Arbitrum-Fans in the community are facing the same issue:_

![image](https://user-images.githubusercontent.com/46747780/159495063-3e5b0963-be16-4fb7-9d4e-1e42360f05d2.png)

![image](https://user-images.githubusercontent.com/46747780/159495304-c1dcf16e-7d6f-4328-80c0-e7369c20052a.png)

![image](https://user-images.githubusercontent.com/46747780/159495478-b4a093c3-df0e-4d4f-b760-6d0c903d171b.png)

[...]

**Comment by TraderVK** [comment]
I confirm I see this error too, quite frequently, even with the latest version

**Comment by TraderVK** [comment]
Adding more information: I've faced situation with where I got this "invalid transaction nonce" error, and then checking on arbiscan.io the transaction was actually sent.
