### ISSUE TITLE
Synchronization takes too long

### ISSUE THREAD

**Issue by vanphandinh** [OffchainLabs/arbitrum#2223]
I'm running an Arbitrum node that connects with my own fully synced Ethereum node using Erigon on the same server.
I see that the Arbitrum node is syncing with about 500-600 blocks/minute, are there any ways to boost the speed up?
Maybe split some block ranges and sync them in parallel. If you're still keeping this speed, we'll have to wait a few weeks to finish the synchronization in the next couple of years.

**Comment by joshuacolvin0** [comment]
Please keep operational questions to discord, thanks
