### ISSUE TITLE
[node version:  1.3.0 ]some transaction can not get internal tx by arbtrace_transaction method. rpc response  code is -32000 and err message is "error creating execution cursor"

### ISSUE THREAD

**Issue by taorzhang** [OffchainLabs/arbitrum#2237]
node has added --node.rpc.tracing.enable params.

[测试网transaction](https://testnet.arbiscan.io/tx/0x95d527204c3c96d575e0529b9dfdb774631023aab25ae40e44f11c30aa4ef1d1)

request:

`{
	"method": "arbtrace_transaction",
	"params": [
		"0x95d527204c3c96d575e0529b9dfdb774631023aab25ae40e44f11c30aa4ef1d1"
	],
	"id": 1,
	"jsonrpc": "2.0"
}`

response:

`{
	"jsonrpc": "2.0",
	"id": 1,
	"error": {
		"code": -32000,
		"message": "error creating execution cursor"
	}
}`

**Comment by gzeoneth** [comment]
I am able to run the trace on my end, can you try to use [v1.3.0-d994f7d](https://hub.docker.com/layers/arb-node/offchainlabs/arb-node/v1.3.0-d994f7d/images/sha256-f2fa2b8b3afabf0737b351e0ceea5d576f6f1c0bf96de8e680c29057fcf87874?context=explore)

**Comment by taorzhang** [comment]
> 

有need to add param: [--node.rpc.tracing.enable]
we upgrade node version to v1.3.0-d994f7d, arbtrace_trasaction is still not stable 。

**Comment by gzeoneth** [comment]
we recently released v1.4.0 with various performance and stability fixes
