### ISSUE TITLE
Review of May 16th

### ISSUE THREAD

**Issue by montyly** [OffchainLabs/arbitrum#2255]
# Week of May 16th

During the week of May 16th, Trail of Bits reviewed 3 PRs:
- L1GatewayRouter refund address entry point https://github.com/OffchainLabs/arbitrum/pull/2107
- Add custom gateway lazy mint on withdrawal https://github.com/OffchainLabs/arbitrum/pull/1713
- Arb-bridge-peripherals e2e test fix https://github.com/OffchainLabs/arbitrum/pull/2218

We run Slither, and manually review the changes. During the assessment, https://github.com/OffchainLabs/arbitrum/pull/2235 was also added to this list, and we performed a best-effort review of it.

### Lack of access control in outboundTransfer
`onlyWhitelisted` was removed from `L1GatewayRouter.outboundTransfer`. The code documentation state that the call to super. `// will revert if msg.sender is not whitelisted` -but this is not true. 

We recommend to Add `onlyWhitelisted` to `L1GatewayRouter.outboundTransfer` and `L1GatewayRouter.outboundTransferCustomRefund`

### Unclear refund alias rules
The documentation states that the refund address will follow the alias remapping rule. The detection is done [`Inbox`](https://github.com/OffchainLabs/arbitrum/blob/token-bridge-develop/packages/arb-bridge-eth/contracts/bridge/Inbox.sol#L337-L339)

`address.isContract(shouldRewriteSender)` will return false is the refund address is a contract, but has no code during the execution. This can happen if:
- The contract is executing its constructor (e.g. the caller is a contract that is currently being deployed). 
- The refund address use a `create2`/`destruct` pattern.

We recommend improving the documentation around the remapping rule, and make it explicit that the refund address must have code for the remapping to work.

This issue also affects the codebase before PR2107 (i.e. if the sender is a contract being deployed).

### Unnecessary assembly usage
The usage of assembly for optimization in [L1GatewayRouter.sol#L231-L234](https://github.com/OffchainLabs/arbitrum/blob/e482169c8fab66a8e537f3523afd295bf1b8fd40/packages/arb-bridge-peripherals/contracts/tokenbridge/ethereum/gateway/L1GatewayRouter.sol#L231-L234) is inefficient and error-prone. 

Changing the location of `_data` to `memory` and using `mload` is more costly than keeping `calldata` with `abi.decode`. In the following code (with optimizer, run 200):
- `Call.test` costs 27,549 gas
- `Call2.test` costs 27,627 gas

```solidity
contract Test{
 
   function test(bytes calldata b) public returns(uint){
           return inter(b);
   }
 
   function inter(bytes calldata b) internal returns(uint){       
       return abi.decode(b, (uint));
   }
 
}
 
contract Call{
   Test t = new Test();
 
   function test() public returns(uint){
       bytes memory b = abi.encode(10, "test");
       return t.test(b);
   }
 
}
 
contract Test2{
 
   function test(bytes calldata b) public returns(uint){
           return inter(b);
   }
 
   function inter(bytes memory b) internal returns(uint){       
       uint v;
       assembly {
           v := mload(add(b, 0x20))
       }
       return v;
   }
 
}
 
contract Call2{
   Test2 t = new Test2();
 
   function test() public returns(uint){
       bytes memory b = abi.encode(10, "test");
       return t.test(b);
   }
 
}
```

As a result the usage of assembly is more costly (because `memory` is more costly than `calldata`). We recommend reverting the changes.

### Fallback function execution
The [try/catch](https://github.com/OffchainLabs/arbitrum/blob/34cdc3bc6b8c741f10b7fa01863cad3189f10d91/packages/arb-bridge-peripherals/contracts/tokenbridge/ethereum/gateway/L1CustomGateway.sol#L116-L118) might lead to execute the fallback function of contract that do not have `bridgeMint`. 

We recommend adding documentation around this corner case, and to consider having `bridgeMint` returning a boolean on success. 

### Lack of events
No event is emitted by `inboundEscrowTransfer`. We recommend adding when `bridgeMint` is executed, so that the monitoring of the system do not rely on the correct event emission of the underlying tokens

### Risky architecture
Offchain labs have explored three alternatives to allow the minting of tokens in L2:
1 - L2 contract can be mint tokens, and when a withdraw happen, L1 tokens can be minted
2 - The creation of a L2 -> L1 transaction when L2 tokens are minted
3 - Force token to first mint on L1, and then transfer it to L2

(1) is the solution currently implemented. However, it contains drawbacks:
- There is no limitation on the L1 minting, if a bug occurs in L2, it could lead to unlimited L1 mint
- It creates two different total supply

(2) would limit the risks, but might still create two different total supply (i.e. the L1 total's total supply would only be updated after the Arbitrum's challenge period)

(3) Remove the risks, but require a L1 call.

While we did not find immediate issues with the implementation of (1), it brings security risks. We recommend considering to following solution (3), or exploring alternatives.

## PR 2218
This PR does not introduce semantics change and only eases the system's testing. As a result we classified it with lower priority and did not uncover a significant issue.

## PR 2235

We reviewed this PR on a best-effort basis. 

- `gasleft() > externalCallGas` in [L2ArbitrumGateway.sol#L421-L433](https://github.com/OffchainLabs/arbitrum/blob/03bb55b5c1936d0838baa639b020d291230beb9c/packages/arb-bridge-peripherals/contracts/tokenbridge/arbitrum/gateway/L2ArbitrumGateway.sol#L421-L433) and [L1ArbitrumGateway.sol#L136-L146](https://github.com/OffchainLabs/arbitrum/blob/03bb55b5c1936d0838baa639b020d291230beb9c/packages/arb-bridge-peripherals/contracts/tokenbridge/ethereum/gateway/L1ArbitrumGateway.sol#L136-L146) might still lead to grieving issue as during the requirements `gasleft >externalCallGas`, but because a couple of opcodes are executed between the requirement execution and the gas call, the call might forward less than `externalCallGas`. Moreover, this does not account for the 63/64 rule. This would require further investigation, but one solution could be to ensure that the user provides a value `externalCallGas` higher than expected, to account for the gas in the gas cost computation.
- `refundAddrOnRevert` and `externalCallGas` are missing from the natspec in all the functions definitions (`outboundTransferWithCall`,  `finalizeInboundTransferAndCall`, ...).
- Consider reverting the `depositAndCalll` if `refundAddrOnRevert` is `0`

**Comment by fredlacs** [comment]
changes were addressed in https://github.com/OffchainLabs/arbitrum/pull/2350
https://github.com/OffchainLabs/arbitrum/pull/1713 was dropped from the current release as we assess the other approaches before we commit to an approach here
issues brought up for https://github.com/OffchainLabs/arbitrum/pull/2235 assessed and will be part of a separate release
