### ISSUE TITLE
Cannot connect to wss://rinkeby.arbitrum.io/feed

### ISSUE THREAD

**Issue by masayil** [OffchainLabs/arbitrum#2280]
![image](https://user-images.githubusercontent.com/65291464/172515737-db09c9f6-f232-4191-b69f-b0f9e942856b.png)
404 NOT FOUND
docker run -d --network host --entrypoint=""  offchainlabs/arb-node:v1.4.1-h9180527 /home/user/go/bin/arb-relay --feed.input.url=wss://rinkeby.arbitrum.io/feed --feed.output.addr="0.0.0.0" --feed.output.port="9642"

**Comment by hkalodner** [comment]
Thanks for the report! The issue is now resolved 🙂
