### ISSUE TITLE
Docs: link to inbox smart contract

### ISSUE THREAD

**Issue by fulldecent** [OffchainLabs/arbitrum#2293]
In https://github.com/OffchainLabs/arbitrum/blob/master/docs/Rollup_basics.md

please link inline to the referred "inbox" smart contract.

**Comment by Andy-Waine** [comment]
Hi @fulldecent, I have submitted a PR for this issue, please let me know if you have any addtl suggestions.

https://github.com/OffchainLabs/arbitrum/pull/2360

**Comment by fulldecent** [comment]
Perfect, thank you
