### ISSUE TITLE
"message":"failed to start inbox reader, waiting and retrying"

### ISSUE THREAD

**Issue by xingdalu** [OffchainLabs/arbitrum#2295]
<img width="580" alt="image" src="https://user-images.githubusercontent.com/71451603/173473901-5ce488a1-130a-48b9-b44b-60b26e5347d5.png">

docker run  -it  --network host offchainlabs/arb-node:v1.4.1-h9180527 --l1.url https://cloudflare-eth.com/

**Comment by joshuacolvin0** [comment]
Please keep all questions about running node to discord, thanks
