### ISSUE TITLE
Please provide officials binaries !

### ISSUE THREAD

**Issue by ytrezq** [OffchainLabs/arbitrum#2342]
Many times building fails because of things like environment/compiler differences, especially in the case of Windows (Win64) or osx.

Providing build scripts is good but because of environment differences, they tend to fail.

An other thing yet better would be database snapshots for `arb-node` in full node mode.

**Comment by gzeoneth** [comment]
We have docker releases [here](https://hub.docker.com/r/offchainlabs/arb-node)

And database snapshots (updated periodically)
Mainnet:
https://snapshot.arbitrum.io/mainnet/db.tar
https://snapshot.arbitrum.io/mainnet/db-archive.tar

Rinkeby:
https://snapshot.arbitrum.io/rinkeby/db.tar
https://snapshot.arbitrum.io/rinkeby/db-archive.tar
