### ISSUE TITLE
Discrepancy in transaction fee calculation

### ISSUE THREAD

**Issue by AstroSnail** [OffchainLabs/arbitrum#2359]
For the sake of example, look at this transaction: https://explorer.arbitrum.io/tx/0xed4ed957aed0031cf06481315214fa8db8874e9cd94cbbbe753dc34095397a0c

This transaction used no value. This means the difference between the balance before and the balance after the transaction is equal to the transaction fee.
```txt
Balance before:   0.004987038082254284 ETH
Balance after:    0.004743691656824420 ETH
Difference (fee): 0.000243346425429864 ETH
```

The total fee for this transaction listed on the explorer is `0.000243346425429864 ETH`, which is correct.

The sum of L1 Fixed + L1 Calldata + L2 Computation + L2 Storage is `0.000243346425429864 ETH`, which is correct.

However, the product of Gas Used × Gas Price Paid is `0.000243346425214424 ETH`, which is lower than the correct number by 215440 wei.

How are Gas Used and Gas Price Paid calculated, and why does their product not equal the real transaction fee?

**Comment by the-emerald** [comment]
Sometimes it overcounts too. See https://explorer.arbitrum.io/tx/0x82a79f9ff4253f7e02c4f014bc97662e125f28eb8f6cc8a9c9bf0b92f912fc4f:
|  | Amount (wei) |
|---|---|
| Before | `1755001001872096957` |
| After | `1754919703204131773` |
| Difference (fee) | `81298667965184` |

However: `0.166407399 gwei` * `488552` is *less* than `81298667965184` wei (`368936` to be exact).

**Comment by gzeoneth** [comment]
Yes, it is possible that `gasUsed * effectiveGasPrice != sum of feeStats` due to arbGas rounding.

**Comment by AstroSnail** [comment]
How are `gasUsed` and `effectiveGasPrice` calculated, and where does this rounding happen? Are there resources I can read to find out more about these calculations?
