### ISSUE TITLE
Late-starting validators catch up slowly

### ISSUE THREAD

**Issue by edfelten** [OffchainLabs/arbitrum#236]
When a validator is started on a chain that has been running for a long time, the validator runs forward through the entire history of the chain, Eth-block by Eth-block, to catch up to the current state. This can take a long time (~20 minutes per day of chain history, currently).  We want to make this faster.

It's already possible to shortcut this by transplanting a checkpoint_db from an existing chain.  (1) Kill an existing validator,  (2) copy the existing validator's checkpoint_db over into the new validator's directory space, (3) restart the old validator, (4) start the new validator.   (We have to kill the existing validator briefly, to avoid a race condition with its update of its db.)

There are at least two things we can do to make catch-up faster. First, we can read the Eth state more efficiently, by finding only the relevant events for our chain, in a way that skips over Eth-blocks that don't have events affecting our chain.

Second, we can come up with a way to serialize the chain and VM state to a file, and post that file at a known public URL.  That would let new validators catch up quickly by restarting from that checkpoint_db.  The "checkpoint" feature of rocksdb could be useful for this.  But we would need a way to deal with the risk that the checkpoint is maliciously inaccurate.

**Comment by edfelten** [comment]
To expand on the point about potentially malicious checkpoints: it's easy to verify that the checkpoint of a VM is correct: just hash the VM and compare it to the hash stored in the rollup state.  The risk is that the checkpoint of the rollup protocol state will be wrong in a malicious way. There doesn't seem to be any simple way of verifying this, given the current code.

**Comment by hkalodner** [comment]
Does the malicious checkpoint issue still occur if you receive the VM state at the latest confirmed assertion?

**Comment by edfelten** [comment]
Yes, I think the malicious checkpoint / state issue still exists.  You can have the VM state accurately, but you also need to be sure that you have the correct state of the rollup protocol (i.e., the state tree).

**Comment by edfelten** [comment]
The hardest part of any recovery strategy would be figuring out which leaf nodes the EthBridge knows about.  The EthBridge can't tell you because it stores them in a map/set data structure that it can't enumerate.  The EthBridge doesn't even know how many leaves it knows about.

The hardest part of catching up is that you would need to learn and verify a full set of leaf nodes in the rollup tree.  One way to do that is to go back in the history until the point where the current latestConfirmed was created, then look at all events going forward from there to find all of the events that created new descendants from that point, and all events that affected the state of those descendants.  By replaying those events, in a way that doesn't break if you don't know about some of the nodes mentioned on those events, you could catch up to the current state.

There would still be some things you didn't know about, such as nodes that are pregnable but not yet pruned -- and stakers would are staked on such nodes.  Not knowing about prunable leaves is not a problem as far as I can see.  But not knowing about stakers on prunable nodes would prevent you from doing some things, such as creating the proofs needed to confirm a new node.

**Comment by hkalodner** [comment]
We added a fast catchup mode which queries events in large batches when they are behind the reorg threshold which solves this problem.
