### ISSUE TITLE
Remove `jayson` dependency

### ISSUE THREAD

**Issue by julientregoat** [OffchainLabs/arbitrum#239]
`jayson` client wraps around all calls to the validator. while it works fine, it abstracts away the logic around the requests unnecessarily, when all we need is the JSON RPC serialization

the JSON RPC 2.0 spec is fairly straightforward and we could implement the serialization ourselves. if this ends up being too much work, [this package](https://www.npmjs.com/package/jsonrpc-lite) could be a quicker solution

**Comment by DZGoldman** [comment]
ape is borked
