### ISSUE TITLE
getTransactionReceipt logIndex is mysteriously set to null

### ISSUE THREAD

**Issue by julientregoat** [OffchainLabs/arbitrum#241]
### tasks
- [ ] figure out & fix `arb-provider-web3` getting receipts from `provider.getTransactionReceipt` with `logIndex` null
- [ ] fix `formatReceipt` function such that it doesn't null `logIndex`

### details
For some reason, when a receipt is retrieved via the `arb-provider-web3` provider,  `logIndex` will be `null`.

This was discovered when an error from `ethers` started appearing in `checkNumber` - it wanted to convert the value to a `BigNumber` but was unable to.

Since the web3 provider is a wrapper around our ethers provider implementation, all calls are proxied to the ethers code. When the `arb-provider-ethers` code returns in `getTransactionReceipt`, the `logIndex` is present. When `arb-provider-web3` gets the result, the `logIndex` has already been set to `null`.

There should be no intermediate modification between these 2 calls, so it doesn't really make sense that the data would be modified.

Here's where things get messy - `(arb-provider-web3).ArbProvider` wraps around `(arb-provider-ethers).ArbProvider` (which inherits from `ethers.provider.BaseProvider`). BaseProvider calls `perform`, which *should* directly call to to the `arb-provider-ethers` library (it's an unimplemented method that throws an error if not).

To make things even more confusing, this was discovered while building our Uniswap demo. That app takes our `(arb-provider-web3).ArbProvider` and uses it to power the `web3-react` package, which rewraps it into an `ethers.js` interface.

While the problem *appears* to be coming from the `ProviderBridge`, there is enough wrapping & inheritance going on that perhaps the data is being further manipulated somewhere in the `ethers` code base.

rough stack trace
- (arb-provider-web3) `ArbProvider.getTransactionReceipt`
- (arb-provider-web3) `ProviderBridge.sendAsync`
- (arb-provider-web3) `ProviderBridge._sendAsync`
- (ethers) `BaseProvider.getTransactionReceipt`
- (arb-provider-ethers) `ArbProvider.perform(getTransactionReceipt)`
- *the trace continues, but the rest has been validated as working properly*

A separate but related problem (happens here)[https://github.com/OffchainLabs/arbitrum/blob/master/packages/arb-provider-web3/ethers-web3-bridge.js#L666]. Even though the `logIndex` is `null` by the time code gets to this line, if one *does* try to populate it before, it will be nulled out again. so `formatReceipt` should be verified.

The current fix is to iterate through the logs and if null, assign indices - either from `transactionLogIndex` if present, or by array position (which should be the same since this is how we assign them in `arb-provider-ethers`). So, if this is a uniswap only issue, it will not adjust indices for any other receipts.

**Comment by hkalodner** [comment]
This is no longer relevant since we've switching over to using a web3 server rather than a plugin
