### ISSUE TITLE
Add missing Nitro Goerli Rollup Testnet (421613) to EVM-based Chains

### ISSUE THREAD

**Issue by marcocastignoli** [OffchainLabs/arbitrum#2413]
Hello, I'm working at [Sourcify](https://sourcify.dev/), we will be adding Sourcify support for 421613. Before proceeding first you need to add Nitro Goerli Rollup Testnet (421613) to EVM-based Chains.

Please add the chain here https://github.com/ethereum-lists/chains

Thanks

**Comment by gzeoneth** [comment]
I see it's added here https://github.com/ethereum-lists/chains/pull/1395, anything else we need to do?

**Comment by marcocastignoli** [comment]
No that's perfect, sorry I reported the missing network two days ago, but I had time to write this issue only today.
Thanks
