### ISSUE TITLE
Installation Error: Easy Fix?

### ISSUE THREAD

**Issue by jmb-42** [OffchainLabs/arbitrum#242]
I'm running Linux Mint 19.2 "Tina" with Cinnamon as my desktop environment.

I ran into some difficulty following the installation guide here:
https://developer.offchainlabs.com/docs/Installation/

I encountered an error when running this code from the above link:

    git clone -b v0.4.2 --depth=1 -c advice.detachedHead=false https://github.com/offchainlabs/arbitrum.git
    cd arbitrum
    yarn
    yarn build
    yarn install:deps

Specifically after running `yarn install:deps`:

    ./scripts/install-deps: line 16: pre-commit: command not found
    error Command failed with exit code 127.

After snooping around the repo I downloaded and the master branch of arbitrum, I found this difference in the scripts.

(on my filesystem) `./arbitrum/scripts/install-deps`:

    15  # Setup pre-commit
    16  pre-commit install

(on the master branch) `https://github.com/offchainlabs/arbitrum/scripts/install-deps`:

    15  # Setup pre-commit
    16  python3 -m pre_commit install

The second one works. The first one does not, which is the error I encountered following the installation guide. I found a branch matching the code I downloaded, which I'm assuming correlates to v0.4.2:
https://github.com/OffchainLabs/arbitrum/tree/version-bump/scripts/install-deps

And I suppose that's the file that needs to be changed, or else maybe the original `git clone` command on the installation page needs to be updated to a more recent version, if it has already been fixed. I hope this is helpful!

**Comment by julientregoat** [comment]
hey @jmb-42, thanks for submitting this issue. yep, you're correct - we fixed this on `master` and need to update our documentation to reflect this.

really appreciate you letting us know!

**Comment by hkalodner** [comment]
This can be closed since this was fixed quite a while ago.
