### ISSUE TITLE
Invalid migrations do not throw errors

### ISSUE THREAD

**Issue by julientregoat** [OffchainLabs/arbitrum#243]
When calling `truffle migrate --network arbitrum`, with or without `--reset`, the contents of the target directory aren't validated on the 2nd or next executions. The contents of the existing JSON files in the `build/contracts` dir appear to be used to determine the migrations that appear to be occurring. 

If the contracts source directory is empty, this process will continue. An error isn't thrown, and the `truffle` output makes it look like it *is* migrated. However, the compiled `contract.ao` will not contain the contract information, and one will be unable to interact with the contract - it will say `contract not deployed`.

UX should probably fail fast if the contract directory doesn't match built JSON, or if a contract directory is empty

**Comment by hkalodner** [comment]
This is no longer relevant since we've removed `arb-provider-ethers`
