### ISSUE TITLE
Question about arbtrace_transaction behavior

### ISSUE THREAD

**Issue by quickchase** [OffchainLabs/arbitrum#2430]
Hello,

It seems this transaction (see below) has no traces on Arbiscan and the response from the nodes gives a `found no trace` error:
```
curl http://localhost:8547/ \
  -X POST \
  -H "Content-Type: application/json" \
  --data '{"method":"arbtrace_transaction","params":["0x3da33d18bf4703acdbe3e73864dbd3dab6f4e759173a0a3540ac85b28cfe3d39"],"id":1,"jsonrpc":"2.0"}'

{"jsonrpc":"2.0","id":1,"error":{"code":-32000,"message":"found no trace"}}
```
https://arbiscan.io/tx/0x3da33d18bf4703acdbe3e73864dbd3dab6f4e759173a0a3540ac85b28cfe3d39

However, this transaction, also with no trace data on Arbiscan, returns a `null` result:
```
curl http://localhost:8547/ \
  -X POST \
  -H "Content-Type: application/json" \
  --data '{"method":"arbtrace_transaction","params":["0x9db5708abe7ddf85ff6155581746fa2658f09d3939f0f4cfd1761df99ec34b4b"],"id":1,"jsonrpc":"2.0"}'

{"jsonrpc":"2.0","id":1,"result":null}
```
https://arbiscan.io/tx/0x9db5708abe7ddf85ff6155581746fa2658f09d3939f0f4cfd1761df99ec34b4b

Could you please help us understand why the behaviors are different here?

**Comment by gzeoneth** [comment]
The reason is that the 2nd tx is a `createRetryableTicket` transaction to Arbitrum precompile which would return `null` during `arbtrace_transaction`
