### ISSUE TITLE
cmake release build step unable to identify Boost libraries location on 1.4.x versions

### ISSUE THREAD

**Issue by eaglecoth** [OffchainLabs/arbitrum#2435]
Hi,

I am trying to build the node on a x64 CentOS8 Machine. This works for tags before 1.4.x.  I.e  tag v1.3.0 works fine. But since v1.4.0 cmake struggles to find boost libraries which are installed (boost and boost-devel packages from dnf).

Boost version: 1.66.0

**Steps to reproduce**:

```
git clone https://github.com/OffchainLabs/arbitrum.git
cd arbitrum
git checkout tags/v1.4.1
git submodule update --init --recursive
yarn
yarn install:deps
cd packages/arb-avm-cpp
mkdir release && cd $_
cmake .. -D CMAKE_PREFIX_PATH=/usr/local/lib -D CMAKE_BUILD_TYPE=Release
```

**Expected outcome:**
Build completes without errors

**Actual outcome:**
+ cmake .. -D CMAKE_PREFIX_PATH=/usr/local/lib -D CMAKE_BUILD_TYPE=Release
-- Found Git: /usr/bin/git (found version "2.27.0") 
-- Submodule update
-- [cable ] Cable 0.5.0 initialized
-- [hunter] Initializing Hunter workspace (13775235910a3fa85644568d1c5be8271de72e1c)
-- [hunter]   https://github.com/cpp-pm/hunter/archive/v0.23.260.tar.gz
-- [hunter]   -> /root/.hunter/_Base/Download/Hunter/0.23.260/1377523
-- Build type: Release
-- The C compiler identification is GNU 9.2.1
-- The CXX compiler identification is GNU 9.2.1
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /opt/rh/gcc-toolset-9/root/usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /opt/rh/gcc-toolset-9/root/usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Found GMP: /usr/lib64/libgmp.so
-- Found GMPXX: /usr/lib64/libgmpxx.so
-- Found OpenSSL: /usr/lib64/libssl.so;/usr/lib64/libcrypto.so;dl (found version "1.1.1k") 
CMake Error at /root/.hunter/_Base/Download/Hunter/0.23.260/1377523/Unpacked/cmake/find/FindBoost.cmake:1273 (message):
  Unable to find the requested Boost libraries.
  Boost version: 1.66.0
  Boost include path: /usr/include
  Could not find the following static Boost libraries:
          boost_filesystem
          boost_system
  No Boost libraries were found.  You may need to set BOOST_LIBRARYDIR to the
  directory containing Boost libraries or BOOST_ROOT to the location of
  Boost.
Call Stack (most recent call first):
  CMakeLists.txt:160 (find_package)

A look in /usr/lib64  shows that the .so files are indeed there and correctly linked:

```
# ls -lart /usr/lib64/libboost_*.so
-rw-r--r-- 1 root root 518 Jun 23 18:31 /usr/lib64/libboost_thread.so
lrwxrwxrwx 1 root root  25 Jun 23 18:32 /usr/lib64/libboost_system.so -> libboost_system.so.1.66.0
lrwxrwxrwx 1 root root  28 Jun 23 18:32 /usr/lib64/libboost_date_time.so -> libboost_date_time.so.1.66.0
lrwxrwxrwx 1 root root  28 Jun 23 18:32 /usr/lib64/libboost_coroutine.so -> libboost_coroutine.so.1.66.0
lrwxrwxrwx 1 root root  26 Jun 23 18:32 /usr/lib64/libboost_context.so -> libboost_context.so.1.66.0
lrwxrwxrwx 1 root root  28 Jun 23 18:32 /usr/lib64/libboost_container.so -> libboost_container.so.1.66.0
lrwxrwxrwx 1 root root  25 Jun 23 18:32 /usr/lib64/libboost_chrono.so -> libboost_chrono.so.1.66.0
lrwxrwxrwx 1 root root  25 Jun 23 18:32 /usr/lib64/libboost_atomic.so -> libboost_atomic.so.1.66.0
lrwxrwxrwx 1 root root  24 Jun 23 18:32 /usr/lib64/libboost_regex.so -> libboost_regex.so.1.66.0
lrwxrwxrwx 1 root root  29 Jun 23 18:32 /usr/lib64/libboost_filesystem.so -> libboost_filesystem.so.1.66.0
lrwxrwxrwx 1 root root  24 Jun 23 18:32 /usr/lib64/libboost_fiber.so -> libboost_fiber.so.1.66.0
lrwxrwxrwx 1 root root  25 Jun 23 18:32 /usr/lib64/libboost_locale.so -> libboost_locale.so.1.66.0
lrwxrwxrwx 1 root root  28 Jun 23 18:32 /usr/lib64/libboost_iostreams.so -> libboost_iostreams.so.1.66.0
lrwxrwxrwx 1 root root  24 Jun 23 18:32 /usr/lib64/libboost_graph.so -> libboost_graph.so.1.66.0
lrwxrwxrwx 1 root root  22 Jun 23 18:32 /usr/lib64/libboost_log.so -> libboost_log.so.1.66.0
lrwxrwxrwx 1 root root  28 Jun 23 18:32 /usr/lib64/libboost_log_setup.so -> libboost_log_setup.so.1.66.0
lrwxrwxrwx 1 root root  27 Jun 23 18:32 /usr/lib64/libboost_math_tr1.so -> libboost_math_tr1.so.1.66.0
lrwxrwxrwx 1 root root  28 Jun 23 18:32 /usr/lib64/libboost_math_tr1l.so -> libboost_math_tr1l.so.1.66.0
lrwxrwxrwx 1 root root  28 Jun 23 18:32 /usr/lib64/libboost_math_tr1f.so -> libboost_math_tr1f.so.1.66.0
lrwxrwxrwx 1 root root  27 Jun 23 18:32 /usr/lib64/libboost_math_c99.so -> libboost_math_c99.so.1.66.0
lrwxrwxrwx 1 root root  28 Jun 23 18:32 /usr/lib64/libboost_math_c99l.so -> libboost_math_c99l.so.1.66.0
lrwxrwxrwx 1 root root  28 Jun 23 18:32 /usr/lib64/libboost_math_c99f.so -> libboost_math_c99f.so.1.66.0
lrwxrwxrwx 1 root root  33 Jun 23 18:32 /usr/lib64/libboost_wserialization.so -> libboost_wserialization.so.1.66.0
lrwxrwxrwx 1 root root  24 Jun 23 18:32 /usr/lib64/libboost_timer.so -> libboost_timer.so.1.66.0
lrwxrwxrwx 1 root root  34 Jun 23 18:32 /usr/lib64/libboost_stacktrace_noop.so -> libboost_stacktrace_noop.so.1.66.0
lrwxrwxrwx 1 root root  35 Jun 23 18:32 /usr/lib64/libboost_stacktrace_basic.so -> libboost_stacktrace_basic.so.1.66.0
lrwxrwxrwx 1 root root  39 Jun 23 18:32 /usr/lib64/libboost_stacktrace_addr2line.so -> libboost_stacktrace_addr2line.so.1.66.0
lrwxrwxrwx 1 root root  26 Jun 23 18:32 /usr/lib64/libboost_signals.so -> libboost_signals.so.1.66.0
lrwxrwxrwx 1 root root  32 Jun 23 18:32 /usr/lib64/libboost_serialization.so -> libboost_serialization.so.1.66.0
lrwxrwxrwx 1 root root  25 Jun 23 18:32 /usr/lib64/libboost_random.so -> libboost_random.so.1.66.0
lrwxrwxrwx 1 root root  34 Jun 23 18:32 /usr/lib64/libboost_program_options.so -> libboost_program_options.so.1.66.0
lrwxrwxrwx 1 root root  35 Jun 23 18:32 /usr/lib64/libboost_prg_exec_monitor.so -> libboost_prg_exec_monitor.so.1.66.0
lrwxrwxrwx 1 root root  38 Jun 23 18:32 /usr/lib64/libboost_unit_test_framework.so -> libboost_unit_test_framework.so.1.66.0
lrwxrwxrwx 1 root root  31 Jun 23 18:32 /usr/lib64/libboost_type_erasure.so -> libboost_type_erasure.so.1.66.0
lrwxrwxrwx 1 root root  23 Jun 23 18:32 /usr/lib64/libboost_wave.so -> libboost_wave.so.1.66.0
```

**Comment by eaglecoth** [comment]
Update: 

It seems that the pre v.1.4.0  tags cannot be built with boost 1.66.  After updating boost to 1.79.0  the problem went away.  I am assuming that the version of FindBoost.cmake  in the Hunter package requires a more recent version of boost

**Comment by gzeoneth** [comment]
We only support the docker build of `arb-node`
