### ISSUE TITLE
rinkeby network rpc problem

### ISSUE THREAD

**Issue by masayil** [OffchainLabs/arbitrum#2447]
docker images:offchainlabs/arb-node:v1.4.1-h9180527
networks:rinkeby
After I resstart the nodes, I get a lot of warn log .Port 8547,8548 can't be exposed, so I cannot use rpc to query the historical data(eg. eth_getbalance)
![image](https://user-images.githubusercontent.com/65291464/183790107-2dead10f-8d28-4368-aafb-c0a0b9a2a85f.png)

docker-compose.yaml
![image](https://user-images.githubusercontent.com/65291464/183790754-dffbcce6-b51b-4a29-b490-c53e96b5ec11.png)

**Comment by gzeoneth** [comment]
try to set `--feed.input.url=""`

**Comment by joshuacolvin0** [comment]
`--feed.input.url=""` is correct.  Updated instructions for running node against Rinkeby is here: https://developer.offchainlabs.com/docs/running_node

In the future, better to ask questions in discord.  Thanks!
