### ISSUE TITLE
Memory leak in arb-node

### ISSUE THREAD

**Issue by nuliknol** [OffchainLabs/arbitrum#2463]
`arb-node` constantly grows in memory during normal operation, and eventually the process is killed by Linux kernel:

```
[462619.604243] Out of memory: Killed process 2529 (arb-node) total-vm:34464336kB, anon-rss:31895656kB, file-rss:0kB, shmem-rss:0kB, UID:1001 pgtables:64676kB oom_score_adj:0
```
In this example the process consumed 30 GB of physical RAM (31895656)
I have nodes with 64GB RAM and the same thing happens, so the size of the memory available doesn't matter

version: 1.4.1

have you checked the executable with valgrind?

**Comment by gzeoneth** [comment]
There are no memory leaks. Each request takes up memory, so if there are a large number of requests per second, there will be a large amount of memory taken up. Recommend a cluster of nodes to share traffic if it is an issue. Note that Nitro has significantly improved performance and memory usage and we will migrate on Aug 31.

**Comment by jacques-martin10** [comment]
> Note that Nitro has significantly improved performance and memory usage and we will migrate on Aug 31.

@gzeoneth do you mean that we should now run the docker image of `offchainlabs/nitro-node` instead of `offchainlabs/arb-node`?

**Comment by gzeoneth** [comment]
yes
only run `arb-node` if you need to serve archive pre-nitro blocks

**Comment by jacques-martin10** [comment]
@gzeoneth that's super cool! 

is the db in `.arbitrum/mainnet` backward compatible? can we run `nitro-node` with the same user folder `.arbitrum/mainnet`?

**Comment by gzeoneth** [comment]
> @gzeoneth that's super cool! 
> 
> 
> 
> is the db in `.arbitrum/mainnet` backward compatible? can we run `nitro-node` with the same user folder `.arbitrum/mainnet`?

They are not compatible, please see https://developer.offchainlabs.com/node-running/running-a-node
