### ISSUE TITLE
submodule err

### ISSUE THREAD

**Issue by anyshy** [OffchainLabs/arbitrum#2486]
v1.4.4

git submodule update --init --recursive
fatal: remote error: upload-pack: not our ref 038d4d908ead0b3154470442c0bf5a95e64891bb
fatal: the remote end hung up unexpectedly
Fetched in submodule path 'packages/go-ethereum', but it did not contain 038d4d908ead0b3154470442c0bf5a95e64891bb. Direct fetching of that commit failed.

**Comment by gzeoneth** [comment]
The ref exists https://github.com/OffchainLabs/go-ethereum/commit/038d4d908ead0b3154470442c0bf5a95e64891bb
Check your network?
