### ISSUE TITLE
Unable to create persistent storage of data

### ISSUE THREAD

**Issue by bmalepaty** [OffchainLabs/arbitrum#2496]
I am running a node through docker image
**Docker Compose File:**
version: '3.3'
 services:  
    arb-node:
        volumes:
            - '../data/:/home/user/.arbitrum/mainnet'
        command:
            - '--l1.url'
            - '<LI_URL>'
            - '--node.cache.allow-slow-lookup'
        ports:
            - '7547:8547'
            - '8548:8548'
        image: 'offchainlabs/arb-node:v1.4.0-f4bbe91'

On 'docker-compose up', getting the following **error**:
![image](https://user-images.githubusercontent.com/77955726/188568582-8f82435c-b175-49e1-a587-40014bb936bb.png)

**Comment by gzeoneth** [comment]
`arb-node` is deprecated, please follow the latest guide to use `nitro-node`
https://developer.offchainlabs.com/node-running/running-a-node

also it seems that your container don't have permission to the mounted directory, you will need to set permission by e.g.
```
chmod -R 777 ../data/
```
