### ISSUE TITLE
Same transaction in two blocks - Arbiscan contradicts with raw response from node

### ISSUE THREAD

**Issue by chaoyandy** [OffchainLabs/arbitrum#2503]
For txn with hash: `0x1d76d3d13e9f8cc713d484b0de58edd279c4c62e46e963899aec28eb648b5800`

In Arbiscan, it gets included in block [4512673](https://arbiscan.io/tx/0x1d76d3d13e9f8cc713d484b0de58edd279c4c62e46e963899aec28eb648b5800) and marked as DUPE in block [4527955](https://arbiscan.io/txs?block=4527955)

However, the raw responses return from node gave us different answer:
request - `{"method":"eth_getTransactionByHash","params":["0x1d76d3d13e9f8cc713d484b0de58edd279c4c62e46e963899aec28eb648b5800"],"id":1,"jsonrpc":"2.0"}`
response - 
```
{
  "jsonrpc": "2.0",
  "id": 1,
  "result": {
    "blockHash": "0x310972fcb862469123a10d3458949d83fd69ff98894a3259cd71dafcf4dd6b37",
    "blockNumber": "0x451753", -> 4527955
    "from": "0x0000000000000000000000000000000000000000",
    "gas": "0xa028",
    "gasPrice": "0x77359400",
    "hash": "0x1d76d3d13e9f8cc713d484b0de58edd279c4c62e46e963899aec28eb648b5800",
    "input": "0x00",
    "nonce": "0x2f",
    "to": "0x97084b650ec71c66fc6178db2e7ab942dd46cf0a",
    "transactionIndex": "0x0",
    "value": "0x16345785d8a0000",
    "type": "0x78",
    "v": "0x0",
    "r": "0x0",
    "s": "0x0"
  }
}
```

So which block actually has this txn? Please help take a look. Thanks!

**Comment by gzeoneth** [comment]
Explained in https://github.com/OffchainLabs/arbitrum/issues/2313
