### ISSUE TITLE
eth_getTransactionReceipt random result on duplicate transactions

### ISSUE THREAD

**Issue by almindor** [OffchainLabs/arbitrum#2537]
Using `eth_getTransactionReceipt` on a transaction hash that has been duplicated such as
```bash
curl -X POST -H 'Content-Type: application/json' -d '{ "id": 43, "method": "eth_getTransactionReceipt", "jsonrpc": "2.0", "params": ["0x1d76d3d13e9f8cc713d484b0de58edd279c4c62e46e963899aec28eb648b5800"]}'
```

results in random return of either
```json
{"jsonrpc":"2.0","id":43,"result":{"blockHash":"0x36789bdc5364f5e1374d7daa35ecfad6cadc8ea5aab8ea38edf8e8178c387b95","blockNumber":"0x44dba1","contractAddress":null,"cumulativeGasUsed":"0x0","effectiveGasPrice":"0x0","from":"0x0000000000000000000000000000000000000000","gasUsed":"0x0","gasUsedForL1":"0x0","l1BlockNumber":"0xd53930","logs":[],"logsBloom":"0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000","status":"0x0","to":"0x97084b650ec71c66fc6178db2e7ab942dd46cf0a","transactionHash":"0x1d76d3d13e9f8cc713d484b0de58edd279c4c62e46e963899aec28eb648b5800","transactionIndex":"0x1","type":"0x78"}}
```

or

```json
{"jsonrpc":"2.0","id":43,"result":{"blockHash":"0x310972fcb862469123a10d3458949d83fd69ff98894a3259cd71dafcf4dd6b37","blockNumber":"0x451753","contractAddress":null,"cumulativeGasUsed":"0x0","effectiveGasPrice":"0x0","from":"0x0000000000000000000000000000000000000000","gasUsed":"0x0","gasUsedForL1":"0x0","l1BlockNumber":"0xd547a4","logs":[],"logsBloom":"0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000","status":"0x0","to":"0x97084b650ec71c66fc6178db2e7ab942dd46cf0a","transactionHash":"0x1d76d3d13e9f8cc713d484b0de58edd279c4c62e46e963899aec28eb648b5800","transactionIndex":"0x0","type":"0x78"}}
```

I haven't been able to identify if the node configuration plays a role in which block is assigned to the receipt.

NOTE: I'm aware arbitrum allows duplicate transactions in separate blocks but `eth_getTransactionReceipt` should be consistent.

**Comment by gzeoneth** [comment]
I am unable to reproduce a situation that the rpc returned the 2nd instance (i.e. the one with blockNumber `0x451753`), which rpc are you using?

**Comment by almindor** [comment]
> I am unable to reproduce a situation that the rpc returned the 2nd instance (i.e. the one with blockNumber `0x451753`), which rpc are you using?

It's the same RPC each time, JSON-RPC over HTTP, exactly like the curl posted. We just change the URL at the end to get this. I can re-try tomorrow to see if our nodes still give the second case.

**Comment by gzeoneth** [comment]
do you mean arb1.arbitrum.io/rpc

**Comment by almindor** [comment]
We get the "wrong" value from nodes hosted in house, I will try to query them again tomorrow to see if it remained consistent and we still get this result from them. I can also, tomorrow, provide the exact command line arguments we use to run them.

**Comment by gzeoneth** [comment]
I see, are you querying a nitro-node forwarding request to the classic arb-node or directly querying the classic node?

**Comment by massif0010** [comment]
nice

**Comment by sujantkumarkv** [comment]
Hey is this issue solved ? Or is there something I can do to help? Let me know the specifics of reproducing the situation, tech-stack and part of the repo to refer. Please as I'm new to the ecosystem. Thanks :)

**Comment by almindor** [comment]
> Hey is this issue solved ? Or is there something I can do to help? Let me know the specifics of reproducing the situation, tech-stack and part of the repo to refer. Please as I'm new to the ecosystem. Thanks :)

I'm no longer working the the client that had this issue. All I can say at this point is they ran their own Arbitrum nodes and their nodes (all of theirs) gave the wrong information about that transaction, while all the public ones returned the correct block. I suspect it's non-deterministic and could be related to node settings.
