### ISSUE TITLE
Migrate away from Yarn

### ISSUE THREAD

**Issue by julientregoat** [OffchainLabs/arbitrum#255]
With the release of `yarn` v2, breaking changes and fundamental differences in its architecture were introduced. Many of these changes are the new defaults, meaning if every package isn't prepared for `yarn`, something will likely break. Unfortunately, it doesn't appear to be a simple migration. It doesn't appear to be completely stable, nor does every published package seem prepared to handle it. React Native isn't supported, and I had a difficult time getting it to work with TypeScript.

related reading:
https://github.com/yarnpkg/berry/issues/843
https://github.com/yarnpkg/berry/issues/766#issuecomment-580658470 (and rest of thread)
https://shift.infinite.red/yarn-1-vs-yarn-2-vs-npm-a69ccf0229cd

possible solutions:

1. We can migrate to `npm`. For monorepo mangement, we can use [`lerna`](https://github.com/lerna/lerna). This is a safe bet long term.

2. We can stay on `yarn 1.x` indefinitely and assess at a later date. Perhaps `yarn v2` will stabilize or adjust the API resulting in a little less friction. If not, we can do solution 1.

pros / cons:
`yarn 1.x` is still faster than `npm`, so it could be worth waiting to see how v2 pans out. but helpful changes for that might take a long time, if ever. one could argue we should switch to `lerna` either way, since the monorepo management should be separate from package management. that decision wouldn't have to affect the usage of `yarn` / `npm`.

**Comment by hkalodner** [comment]
I think the way things are developing, it looks like yarn 1.x is going be supported indefinitely because of the push against 2.0. I'm going to close this for now since I think sticking with the status quo makes sense. We can revisit this decision later.

**Comment by merceyz** [comment]
I'll just leave this here as a note.

Yarn 2 supports installs using `node_modules` as well, so if PnP doesn't work for you / you can't invest the time to fix all packages that don't declare their dependencies correctly you always have that option.
```
yarn set version 2 && yarn config set nodeLinker node-modules
```
