### ISSUE TITLE
Feature request: ability to use ssd as cache and HDD as storage to run nitro node

### ISSUE THREAD

**Issue by JJassonn69** [OffchainLabs/arbitrum#2574]
I have been running arbitrum nitro for a while now but my 1TB ssd is just about to be full, I tried switching to HDD but the input output is slow that when there is surge in network the node doesnt sync to the latest block.

I was hoping if there was a way to use SSD as cache and HDD as main storage while running nitro.

**Comment by zhy827827** [comment]
zfs

**Comment by TucksonDev** [comment]
Hello!
This repository holds the code for the classic node stack and is deprecated. No further developments are being made, other than security fixes.
The current **nitro** node stack software can be found [here](https://github.com/OffchainLabs/nitro/).
I'll close this issue now, but don't hesitate to contact us through the Nitro repository or [Discord](https://discord.com/invite/arbitrum) to solve any issues you may be encountering.
