### ISSUE TITLE
please increase rate limit from our own nodes on your sequencer !

### ISSUE THREAD

**Issue by tardigralice** [OffchainLabs/arbitrum#2579]
Hello, we are sharing a arbitrum node with 5 friends, and we are often blocked because of the "rate limit"

`error: Public RPC Rate Limit Hit, limit will reset in 60 seconds`

We are not Ddos anyone, we are just heavily using our OWN node, like on any normal chain.

Can you increase the rate limit please ?

**Comment by Tristan-Wilson** [comment]
Hi,

Can you please open a ticket at https://support.arbitrum.io/hc/en-us describing your use case and providing information we can use to identify your requests such as the IP address they are originating from, so that we can diagnose this issue.
