### ISSUE TITLE
Ensure no collisions between Arbitrum and Ethereum transaction hashes

### ISSUE THREAD

**Issue by hkalodner** [OffchainLabs/arbitrum#304]
In `arb-provider-ethers` we rely on the assumption that Arbitrum transaction hashes will not collide with Ethereum transaction hashes. We need to make sure that this assumption is correct, and if it is not, we'll have to figure out how we can adjust the structure of our hashes.

Currently this assumption is used in `getMessageResult` in `arb-provider-ethers`

**Comment by edfelten** [comment]
Closing this, because the current implementation uses Chain IDs to ensure non-portability of transactions.
