### ISSUE TITLE
Make rollup Merkle proofs shorter

### ISSUE THREAD

**Issue by edfelten** [OffchainLabs/arbitrum#318]
The rollup protocol requires validators to submit Merkle proofs to the EthBridge, to prove the existence or properties of rollup state nodes.  Under some conditions those Merkle proofs might get large.  We want them to be smaller.

One approach to do this is to add an "express lane" for the proofs, which allows the proof to jump many steps forward in the tree, all at once.  For example, in addition to each node containing the hash of its parent, we could also have it include the hash of its last predecessor whose depth is a multiple of some "step size" S.   Long Merkle proofs would use this "express lane" to get close to their destination, then switch to the "local lane" to take the last few steps.

The express lane hash is easy to compute when making a new node.  If the new node's depth mod S is 1, then the express lane hash is just the hash of the parent node; otherwise the express lane hash is equal to the parent node's express lane hash.

This could be done at multiple levels if we want.

To be safe, we might have two levels of express lanes, at S=32 and S=1024.

**Comment by hkalodner** [comment]
The new rollup protocol increase on-chain costs slightly in order to entirely remove the need for proofs from the main rollup protocol
