### ISSUE TITLE
Smart Contracts can be deployed to address with private keys

### ISSUE THREAD

**Issue by hkalodner** [OffchainLabs/arbitrum#324]
Currently we allow contracts to be deployed at arbitrary addresses. There's nothing stopping a malicious rollup creator from deploying a contract at an address which they also possess a private key for. If this occurred, they would be able to make transactions as that contract, allowing them to drain its funds.

Possible Solutions:
- This issue can be fixed when we add support for installation of contracts into an already running VM. At that point the Arbitrum runtime will calculate the address of newly deployed contracts.
- We could allow the client to verify that a contract address is valid by providing the inputs to the address generation algorithm that produced that contract address and throw an error if you try to interact with a smart contract without a valid proof.

Personally I'd say we should go with the first option, though it will delay the solving of this issue. The second option feels fairly hacky, but could potentially be implemented sooner.

**Comment by edfelten** [comment]
Agree that we should be using trusted code (e.g. in the EthBridge) to generate contract addresses.  This connects to the issue of how to ensure that the correct L2 runtime is running in each chain (which allows the L2 runtime to be fully trusted, assuming AnyTrust).

I think we should consider an approach where every chain starts with just the trusted runtime (enforced by the EthBridge), then contracts are deployed onto the chain via the trusted runtime.  That lets the trusted runtime check the safety of all contracts.

**Comment by hkalodner** [comment]
With the switch to ArbOS, the rollup chain starts with no contracts deployed and then generates addresses on deployment in the same style as ethereum which fixes this issue
