### ISSUE TITLE
number of arguments mismatch with depositERC20Message & depositERC721Message

### ISSUE THREAD

**Issue by DZGoldman** [OffchainLabs/arbitrum#505]
Both methods currently throw an error: they're called with a 5th `overrides` parameter in `l1Bridge.ts` which is missing in the implementations (in `GlobalInbox.sol`).

**Comment by hkalodner** [comment]
I don't understand why this doesn't work with the autogenerated typechain interface https://github.com/OffchainLabs/arbitrum/blob/d4dc5a2c596880614d41119a13b90c09922d08de/packages/arb-provider-ethers/src/lib/abi/GlobalInbox.d.ts#L287

**Comment by hkalodner** [comment]
This is now fixed
