### ISSUE TITLE
Add Support for Arbitrum Rollup

### ISSUE THREAD

**Issue by hkalodner** [OffchainLabs/arbitrum#58]
Until now development within the Arbitrum codebase has focused exclusively on the implementation of what we refer to as Arbitrum Channels. In a recent blog post, https://medium.com/offchainlabs/how-to-choose-your-validators-in-arbitrum-f04c8797bbef, @ewfelten clarified how Arbitrum Channels work and introduced a new concept, Arbitrum Chains.

Implementation of Arbitrum chains should be relatively straightforward. The main differences are the addition of a method for validators to join and leave a VM at will and the disabling of unanimous assertions in order to force all messages on-chain to guarantee data availability for newly joining validators.

**Comment by hkalodner** [comment]
As of #74 we now have most of the machinery for basic Arbitrum chains integrated into the codebase. The major remaining feature is to add coordination and progress mechanisms for the validators.

**Comment by ewfelten** [comment]
Renamed this issue because we now call (the improved version of) this feature Arbitrum Rollup.

**Comment by ewfelten** [comment]
Closing, because master now supports Rollup.
