### ISSUE TITLE
Update AVM spec to match new inbox semantics

### ISSUE THREAD

**Issue by ewfelten** [OffchainLabs/arbitrum#65]
We have changed the semantics of VM inboxes since we last updated the AVM spec. Need to update spec to reflect the fact that Inbox instruction now empties the inbox.

**Comment by hkalodner** [comment]
This hasn't been updated in the VM implementations later yet. We need to finish specifying those changes first and then make this update simultaneously.

**Comment by ewfelten** [comment]
Fix has been merged into master.
