### ISSUE TITLE
Make it easier for contracts to send messages to Arbitrum on-chain

### ISSUE THREAD

**Issue by hkalodner** [OffchainLabs/arbitrum#69]
Arbitrum VMs expect to receive messages as marshaled values which are the encoding of solidity calldata. Currently client-side providers perform this conversion seemlessly making the programming experience indistinguishable from writing calls to normal Ethereum contracts. However there is no current on-chain equivalent to this functionality.

It would be awesome to have a contract interface generator which took the abi of a compiled Arbitrum contract, extracted the list of mutating functions, and generated a contract to be deployed on Ethereum with those same functions which would convert calldata into the proper Arbitrum value format and send those messages on-chain to the VM.

**Comment by ewfelten** [comment]
Fixed by #203.
