### ISSUE TITLE
getMessageResult fails when MacOS locked and turned on again

### ISSUE THREAD

**Issue by ughe** [OffchainLabs/arbitrum#7]
## Steps to reproduce:

- Run `demo-dapp-pet-shop` on MacOS Mojave
- Adopt some pets
- Lock the computer
- Unlock and try to adopt another pet (should hang)
- Reloading will show pet was adopted, however will still hang on subsequent adoption clicks

## Error:

The dapp hangs on the following line:

https://github.com/OffchainLabs/arb-ethers-provider/blob/2182c185c38cb45a9771324998eab337c4777a4b/lib/index.js#L154

**Comment by hkalodner** [comment]
This is no longer an issue since we switched to using a json-rpc server
