### ISSUE TITLE
arb-bridge-eth fails to compile with solc 0.5.11

### ISSUE THREAD

**Issue by hkalodner** [OffchainLabs/arbitrum#73]
Currently arb-bridge-eth compiles fine with solc 0.5.10, but fails with solc 0.5.11 with the following error
```
Internal compiler error during compilation:
/tmp/solidity-20190917-49278-19sfpot/solidity_0.5.11/libsolidity/ast/Types.cpp(2053): Throw in function virtual bool dev::solidity::StructType::isDynamicallyEncoded() const
Dynamic exception type: boost::wrapexcept<langutil::InternalCompilerError>
std::exception::what:
[dev::tag_comment*] =
```

For now we can just stick with requiring an old version of the solidity compiler, but at some point we will require either an upstream fix or a mitigation strategy to avoid hitting this bug.

**Comment by hkalodner** [comment]
This bug occurs due to some code in ArbValue. We could potentially solve this problem on our end if necessary, but I opened a bug report in the compiler (https://github.com/ethereum/solidity/issues/7448) with a small reproducible sample. Hopefully we'll get a fix in the next version since this appears to be a regression.🤞

**Comment by ewfelten** [comment]
Closing this, because the underlying Solidity compiler bug appears to have been fixed.
