### ISSUE TITLE
arb-validator docker error with python3-dev=3.6.8-r2

### ISSUE THREAD

**Issue by whalelephant** [OffchainLabs/arbitrum#83]
In `packages/arb-validator.Dockerfile` the docker `RUN` command uses `python3-dev=3.6.8-r2`

This gave the following error:
```
ERROR: unsatisfiable constraints: python3-dev-3.6.9-r2: breaks: world[python3-dev=3.6.8-r2]
```
The use of `python3-dev=3.6.9-r2` was able to avoid the error

**Comment by hkalodner** [comment]
Fixed by #82
