### ISSUE TITLE
Internet Connection Required

### ISSUE THREAD

**Issue by ughe** [OffchainLabs/arbitrum#9]
This dapp tries to connect to: animalso.com and googleapis.com

https://github.com/OffchainLabs/demo-dapp-pet-shop/blob/e82c3b748680f6aea53da52b889c4d7de831b7e0/dist/index.html#L42

https://github.com/OffchainLabs/demo-dapp-pet-shop/blob/e82c3b748680f6aea53da52b889c4d7de831b7e0/dist/index.html#L54

By removing these external sources, local development could occur offline

**Comment by ewfelten** [comment]
Labeled this wontfix.  Not worth the trouble to fix, because this demo will be replaced.
